---
- name: Test create_file role
  hosts: localhost
  connection: local
  gather_facts: no
  
  roles:
    - role: create_file
      vars:
        create_file_path: "/tmp/role_test_1.txt"
        create_file_content: "File created by role test 1"
    
    - role: create_file
      vars:
        create_file_path: "/tmp/role_test_2.txt"
        create_file_content: "File created by role test 2"
        create_file_force: true
